/*
  DESIGN TOKENS — ROMANTIC PALETTE
  bg-void #170a12 | panel rgba(42,20,32,.5) | rose #e0849f
  plum #9c5a82 | gold #d9a463 | text #f7ece2 | muted #b98a9a
  display: 'Chakra Petch' (system labels) | body: 'Tajawal'
  signature: heart-scanner intro + reconnect charge button + sealed
  love-letter envelope — all rendered in warm romantic wine/rose/gold tones.
*/

export const S = {
  root: {
    minHeight: "100vh",
    background: "#170a12",
    color: "#f7ece2",
    fontFamily: "'Tajawal', sans-serif",
    position: "relative",
    overflowX: "hidden",
  },
  canvas: { position: "fixed", inset: 0, zIndex: 0, width: "100%", height: "100%" },
  center: {
    position: "relative",
    zIndex: 2,
    minHeight: "100vh",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    textAlign: "center",
    padding: 24,
    gap: 14,
  },
  sysLabel: {
    fontFamily: "'Chakra Petch', monospace",
    letterSpacing: 3,
    fontSize: 13,
    color: "#d9a463",
    textTransform: "uppercase",
    marginBottom: 10,
  },
  sysLabelSmall: {
    fontFamily: "'Chakra Petch', monospace",
    letterSpacing: 1,
    fontSize: 12,
    color: "#b98a9a",
  },
  bootTitle: {
    fontFamily: "'Tajawal', sans-serif",
    fontWeight: 800,
    fontSize: "clamp(24px,4.5vw,38px)",
    color: "#f7ece2",
    margin: "6px 0 20px",
    textShadow: "0 0 24px rgba(156,90,130,0.6)",
  },
  neonBtn: {
    background: "linear-gradient(135deg,#e0849f,#9c5a82)",
    color: "#fff",
    border: "none",
    borderRadius: 999,
    padding: "14px 30px",
    fontSize: 15,
    fontWeight: 700,
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    cursor: "pointer",
    fontFamily: "'Tajawal', sans-serif",
    boxShadow: "0 0 26px rgba(224,132,159,0.45)",
  },
  neonBtnOutline: {
    background: "transparent",
    border: "1.5px solid #d9a463",
    color: "#d9a463",
    borderRadius: 999,
    padding: "12px 26px",
    fontSize: 14,
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    cursor: "pointer",
    fontFamily: "'Tajawal', sans-serif",
  },
  terminal: {
    background: "rgba(26,14,18,0.75)",
    border: "1px solid rgba(217,164,99,0.3)",
    borderRadius: 14,
    padding: "22px 26px",
    width: "100%",
    maxWidth: 440,
    textAlign: "right",
    backdropFilter: "blur(10px)",
  },
  terminalLine: {
    fontFamily: "'Chakra Petch', monospace",
    fontSize: 13.5,
    color: "#b98a9a",
    margin: "4px 0",
  },
  terminalDone: {
    fontFamily: "'Tajawal', sans-serif",
    fontSize: 15.5,
    lineHeight: 1.8,
    color: "#b98a9a",
    margin: "4px 0",
  },
  terminalTyped: {
    fontFamily: "'Tajawal', sans-serif",
    fontSize: 17,
    lineHeight: 1.9,
    color: "#f7ece2",
    minHeight: 30,
  },
  progressTrack: {
    height: 6,
    background: "#2a1420",
    borderRadius: 4,
    overflow: "hidden",
    margin: "14px 0 6px",
  },
  progressFill: {
    height: "100%",
    background: "linear-gradient(90deg,#d9a463,#9c5a82,#e0849f)",
    transition: "width 0.1s linear",
  },
  main: { position: "relative", zIndex: 2, maxWidth: 720, margin: "0 auto", padding: "0 20px" },
  section: {
    minHeight: "90vh",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    padding: "60px 0",
    textAlign: "center",
  },
  h2: {
    fontFamily: "'Tajawal', sans-serif",
    fontWeight: 800,
    fontSize: "clamp(22px,3.6vw,30px)",
    margin: "0 0 26px",
    textShadow: "0 0 18px rgba(224,132,159,0.35)",
  },
  h2small: { fontFamily: "'Tajawal', sans-serif", fontWeight: 800, fontSize: 19, margin: "4px 0" },
  scannerWrap: {
    position: "relative",
    width: 200,
    height: 200,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 18,
  },
  scannerRing: {
    position: "absolute",
    inset: 0,
    borderRadius: "50%",
    border: "2px solid rgba(217,164,99,0.35)",
  },
  scannerRing2: {
    position: "absolute",
    inset: 24,
    borderRadius: "50%",
    border: "1px solid rgba(224,132,159,0.3)",
  },
  pctText: {
    fontFamily: "'Chakra Petch', monospace",
    fontSize: 22,
    color: "#e0849f",
    marginTop: 4,
  },
  glassCard: {
    background: "rgba(42,20,32,0.55)",
    border: "1px solid rgba(156,90,130,0.35)",
    borderRadius: 18,
    padding: "26px 24px",
    backdropFilter: "blur(12px)",
    marginTop: 20,
    maxWidth: 480,
  },
  arabicBody: { fontSize: 17, lineHeight: 2, color: "#f7ece2", margin: 0 },
  capsuleLabel: { fontFamily: "'Tajawal', sans-serif", fontWeight: 700, fontSize: 14 },
  capsuleText: { fontSize: 13, lineHeight: 1.65, color: "#f7ece2", margin: 0 },
  installText: { fontSize: 15.5, color: "#f7ece2" },
  bars: {
    display: "flex",
    gap: 3,
    justifyContent: "center",
    alignItems: "flex-end",
    height: 34,
    marginTop: 22,
  },
  chargeWrap: {
    position: "relative",
    width: 180,
    height: 180,
    margin: "10px auto",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  chargeBtn: {
    position: "absolute",
    width: 88,
    height: 88,
    borderRadius: "50%",
    background: "linear-gradient(135deg,#e0849f,#9c5a82)",
    border: "none",
    color: "#fff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    boxShadow: "0 0 30px rgba(224,132,159,0.5)",
    userSelect: "none",
  },
  timelineWrap: { position: "relative", width: "100%", maxWidth: 480, padding: "10px 0" },
  timelineLine: {
    position: "absolute",
    right: 15,
    top: 0,
    bottom: 0,
    width: 2,
    background: "linear-gradient(180deg,#d9a463,#e0849f,#9c5a82)",
    opacity: 0.4,
  },
  timelineDot: {
    position: "absolute",
    right: 4,
    width: 24,
    height: 24,
    borderRadius: "50%",
    background: "linear-gradient(135deg,#e0849f,#9c5a82)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    boxShadow: "0 0 14px rgba(224,132,159,0.6)",
  },
  timelineCard: {
    marginRight: 46,
    background: "rgba(42,20,32,0.5)",
    border: "1px solid rgba(217,164,99,0.25)",
    borderRadius: 12,
    padding: "12px 16px",
    textAlign: "right",
  },
  timelineKey: { fontWeight: 800, fontSize: 15, color: "#d9a463", margin: "0 0 4px" },
  timelineDesc: { fontSize: 13.5, color: "#f7ece2", margin: 0, lineHeight: 1.6 },
  heartsLayer: { position: "fixed", inset: 0, zIndex: 1, pointerEvents: "none", overflow: "hidden" },
  envelopeTo: {
    fontFamily: "'Chakra Petch', monospace",
    fontSize: 13,
    letterSpacing: 1,
    color: "#b98a9a",
  },
  letterText: { fontSize: 15, lineHeight: 1.9, color: "#3a1420", margin: "0 0 10px" },
  letterSign: { fontSize: 14, fontWeight: 800, color: "#b0446e", margin: 0 },
};
